---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - release
jobs:
  cdk:
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn test
      - name: build docs
        if: github.ref == 'refs/heads/release'
        run: yarn docs
      - name: save docs to artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
      - name: build
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
        run: yarn build
      - name: release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
        run: yarn semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
  docs:
    needs: cdk
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: download docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs
      - name: publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
  create-release-pull-request:
    needs: cdk
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - run: |
          git fetch origin main:main
          git reset --hard main
      - name: create release pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          title: Publish release
          base: release
