---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - release
jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1.1.2
        with:
          go-version: 1.13.x
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: make
        run: make
  cdk:
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: bootstrap
        run: yarn bootstrap
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: build docs
        if: github.ref == 'refs/heads/release'
        run: yarn workspace @aereal/qron typedoc src/
      - name: save docs to artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: packages/@aereal/qron/docs
      - name: release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
        run: yarn workspace @aereal/qron semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
  docs:
    needs: cdk
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: download docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: packages/@aereal/qron/docs
      - name: publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/@aereal/qron/docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
